name: Turquoise Space - Open JDK 8 - Docker Image CI / CD

on:
  push:
    branches: [ "main" ]

jobs:

#  test:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Test
#      run: echo "Username is ${{ secrets.DockerHub_UserName }}"

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
#          registry: index.docker.io/v1/
          registry: https://registry.hub.docker.com/v2
#          registry: registry.hub.docker.com/library
          username: ${{ secrets.DockerHub_UserName }}
          password: ${{ secrets.DockerHub_PassWord }}
          logout: true
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: turquoisespace/open-jdk-8:jdk8u362-b09_jre_x64_alpine-linux_hotspot
