name: Turquoise Space - Open JDK 8 - Docker Image CI / CD

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
#        run: docker buildx inspect --bootstrap
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://registry.hub.docker.com/v2
          username: ${{ secrets.DockerHub_UserName }}
          password: ${{ secrets.DockerHub_PassWord }}
          logout: true
      -
        name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          load: true
#          platforms: linux/amd64
          tags: |
            turquoisespace/open-jdk-8:jdk8u362-b09_jre_x64_alpine-linux_hotspot
            turquoisespace/open-jdk-8:${{ github.sha }}
            turquoisespace/open-jdk-8:latest_jre_x64_alpine-linux_hotspot
      -
        name: Image digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}
